// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_get_lyric_from_lofty`, `_get_lyric_from_lrc_file`, `_get_picture_by_lofty`, `_get_picture_by_windows`, `_update_index_below_1_1_0`, `new_with_path`, `read_by_lofty`, `read_by_win_music_properties`, `read_from_folder_recursively`, `read_from_folder`, `read_from_path`, `to_json_value`, `to_json_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioFolder`, `Audio`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

/// for Flutter
/// 如果无法通过 Lofty 获取则通过 Windows 获取
Future<Uint8List?> getPictureFromPath(
        {required String path, required int width, required int height}) =>
    RustLib.instance.api.crateApiTagReaderGetPictureFromPath(
        path: path, width: width, height: height);

/// for Flutter
/// 只支持读取 ID3V2, VorbisComment, Mp4Ilst 存储的内嵌歌词
/// 以及相同目录相同文件名的 .lrc 外挂歌词（utf-8 or utf-16）
Future<String?> getLyricFromPath({required String path}) =>
    RustLib.instance.api.crateApiTagReaderGetLyricFromPath(path: path);

/// for Flutter
/// 扫描给定路径下所有子文件夹（包括自己）的音乐文件并把索引保存在 index_path/index.json。
Stream<IndexActionState> buildIndexFromFoldersRecursively(
        {required List<String> folders, required String indexPath}) =>
    RustLib.instance.api.crateApiTagReaderBuildIndexFromFoldersRecursively(
        folders: folders, indexPath: indexPath);

/// for Flutter
/// 读取 index_path/index.json，递归扫描已配置目录。
///
/// 文件以规范化绝对路径匹配。新增、删除、修改时间或大小变化的文件会更新索引；
/// 未变化文件保留既有标签。写入通过临时文件替换，以便扫描失败时保留原索引。
Stream<IndexActionState> updateIndex({required String indexPath}) =>
    RustLib.instance.api.crateApiTagReaderUpdateIndex(indexPath: indexPath);

class IndexActionState {
  /// completed / total
  final double progress;

  /// describe action state
  final String message;

  const IndexActionState({
    required this.progress,
    required this.message,
  });

  @override
  int get hashCode => progress.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexActionState &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          message == other.message;
}
